### ISSUE TITLE
現場で使えるrails7章

### ISSUE THREAD

**Issue by riku1027** [rexitorg/menta#63]
## 概要
現場で使えるrailsを読みながら本の通りにtaskleafアプリを作っていたのですが、7章で始めたあたりでrails s をしてもserverが立ち上がらなくなりました。
config.ruが見つからないと言われたのですが、探してみたところtaskleaf内にはちゃんと入っていました。何故ちゃんと読み込まれない？のかがわからないです。ご教授いただけると幸いです。

## 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
```
$ rails s
=> Booting Puma
=> Rails 5.2.2.1 application starting in development 
=> Run `rails server -h` for more startup options
configuration config.ru not found
Exiting
```
```vendor/config.ru

# This file is used by Rack-based servers to start the application.

require_relative 'config/environment'

run Rails.application

```

## 解決するために行ったこと
https://railsguides.jp/rails_on_rack.html#rackup%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89　
上を参考にしてrackup コマンドでサーバーを起動してみました。
```
$ rackup config.ru
configuration /Users/takahashiriku/Desktop/taskleaf/config.ru not found
```
だめっぽかったので指定先を変えてみました。
```
macpro:taskleaf takahashiriku$ rackup vendor/config.ru
Traceback (most recent call last):
	16: from /Users/takahashiriku/.rbenv/versions/2.5.1/bin/rackup:23:in `<main>'
	15: from /Users/takahashiriku/.rbenv/versions/2.5.1/bin/rackup:23:in `load'
	14: from /Users/takahashiriku/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/bin/rackup:4:in `<top (required)>'
	13: from /Users/takahashiriku/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/server.rb:148:in `start'
	12: from /Users/takahashiriku/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/server.rb:283:in `start'
	11: from /Users/takahashiriku/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
	10: from /Users/takahashiriku/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
	 9: from /Users/takahashiriku/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	 8: from /Users/takahashiriku/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
	 7: from /Users/takahashiriku/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
	 6: from /Users/takahashiriku/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
	 5: from /Users/takahashiriku/Desktop/taskleaf/vendor/config.ru:in `<main>'
	 4: from /Users/takahashiriku/Desktop/taskleaf/vendor/config.ru:in `new'
	 3: from /Users/takahashiriku/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
	 2: from /Users/takahashiriku/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
	 1: from /Users/takahashiriku/Desktop/taskleaf/vendor/config.ru:3:in `block in <main>'
/Users/takahashiriku/Desktop/taskleaf/vendor/config.ru:3:in `require_relative': cannot load such file -- /Users/takahashiriku/Desktop/taskleaf/vendor/config/environment (LoadError)
```

**Comment by konchanxxx** [comment]
> config.ruが見つからないと言われたのですが、探してみたところtaskleaf内にはちゃんと入っていました。何故ちゃんと読み込まれない？のかがわからないです。ご教授いただけると幸いです。

これはファイルが削除されていたりすると @riku1027 sanのPCに保存しているソースファイルの状態に依存するので現時点でのソースコードをGitHubにあげて頂きたいです:bow:
可能でしょうか？
rackupコマンドはRailsであれば通常使う必要ないので他の対処法が望ましいと思います:bow:

**Comment by konchanxxx** [comment]
> 現場で使えるrailsを読みながら本の通りにtaskleafアプリを作っていたのですが、7章で始めたあたりでrails s をしてもserverが立ち上がらなくなりました。

あとこまめにgitでcommitして常に動く状態の箇所まで遡れるようにしておいた方が良いと思います:bow:

**Comment by riku1027** [comment]
なるほど。これからはちゃんとgitで管理するようにします💦
以下がgithubページです
https://github.com/riku1027/taskleaf
よろしくお願いします！

**Comment by konchanxxx** [comment]
ありがとうございます:bow: 確認します！:bow:

**Comment by konchanxxx** [comment]
config.ruファイルを何かのタイミングで削除してしまっているみたいですね。もしくはどこかにドラッグ&ドロップする際に移動してしまったとか

`taskleaf`のディレクトリの直下に`config.ru`ファイルを下記の内容で作成したら動作しました:bow:
作成してみてください:bow:

`taskleaf/config.ru`

```rb
# This file is used by Rack-based servers to start the application.

require_relative 'config/environment'

run Rails.application
```

**Comment by konchanxxx** [comment]
@riku1027

**Comment by riku1027** [comment]
ありがとうございます(T . T)ちゃんと動作しました！
taskleafではなくvendor直下にconfig.ruが入ってたみたいでした

**Comment by konchanxxx** [comment]
@riku1027 
Gitで管理しておくと間違ってファイル動かしちゃった時に元に戻せたりして便利なので活用してみてください！:smile:
